spring.application.name=mission
server.address=0.0.0.0
spring.jpa.show-sql=true
# Swagger 경로 명시적 활성화
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.use-suffix-pattern=false